title: Hamza Mecca # your name (or website title) here
logo:  "/images/profile_picture2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hey! Im a business analyst with 3+ years of experience. I've founded my own tech startup (passionfruitmusic.com) and worked with big clients in the apparel industry.
  <br><br>
  I'm proficient with SQL, R, and Tableau. Check out my projects on the right! 
  <br><br>
  I've included a case study and am currently working on 3 more projects. One of these will be related to fantasy premier league as I am a combining sports and strategy :) 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
